name: colorsgenerator
description: Test task.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.12


flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf